spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: "705139499171-k4k67ire5g2qn0q4.apps.googleusercontent.com"
            client-secret: "GOCSPX-_dre5RwvLQiK2SFrKEvuyhGJ"
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
            authorization-grant-type: authorization_code
          github:
            client-id: "Ov23liMOjoKiS4tIx"
            client-secret: "00308b711c2bc6951d4544c33d7243cf0"
            scope:
              - read:user                                # GitHub's scope for name/avatar
              - user:email                               # Separate scope needed for email
            redirect-uri: "http://localhost:8081/login/oauth2/code/github"
            authorization-grant-type: authorization_code

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          # GitHub provider is built into Spring Security — no manual provider
          # config needed. Spring knows GitHub's endpoints automatically.

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: "Ph@ssain2025"
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      mandatory: true
      receive-timeout: 5000
      reply-timeout: 5000
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 5
        max-concurrency: 20
        prefetch: 10

  cache:
    type: redis

    data:
      redis:
        host: localhost
        port: 6379
        timeout: 2s
        max-requests: 5
        window-seconds: 100

        lettuce:
          pool:
            max-active: 16
            max-idle: 16
            min-idle: 4

#  rate-limiter:
#    type: redis

rate-limiter:
  type: memory
  max-requests: 2
  window-seconds: 30

  mail:
    host: smtp.gmail.com
    port: 587
    username: parvezhossain724@gmail.com
    password: gmjdrtdctn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.security: INFO

jwt:
  secret: "HNdUQ6/rEbglkRb89eNEwvQuHASmRHDdZUx6obVLAS0="
  expiration: 3600000
  refresh-expiration: 36000000

app:
  pagination:
    max-size: 100